# Generated by Django 3.0 on 2020-01-09 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cat_desc', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categoria',
            },
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('res_fech_prestamo', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LibroModel',
            fields=[
                ('libro_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('libro_nombre', models.CharField(max_length=45)),
                ('libro_disp', models.BooleanField(default=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelita.CategoriaModel')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'db_table': 'Libros',
            },
        ),
    ]
