# Generated by Django 3.0 on 2020-01-09 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuelita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libromodel',
            name='usu_id',
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='libro_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='escuelita.LibroModel'),
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='usu_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
