# Generated by Django 3.0 on 2020-01-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelita', '0003_auto_20200109_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamodel',
            name='res_fech_devolucion',
            field=models.DateTimeField(default=None),
        ),
    ]
