# Generated by Django 3.0 on 2020-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelita', '0004_reservamodel_res_fech_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamodel',
            name='res_fech_devolucion',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
