# Generated by Django 3.0 on 2020-01-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('prod_nombre', models.CharField(max_length=45)),
                ('prod_cantidad', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_productos',
            },
        ),
        migrations.CreateModel(
            name='VentaModel',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('venta_cantidad', models.IntegerField()),
                ('venta_cajero', models.IntegerField()),
                ('venta_fecha', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tienda.ProductoModel')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 't_venta',
            },
        ),
    ]
